<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# Peer Review Assignment - Data Engineer - Extract API Data

Estimated time needed: **20** minutes

## Objectives

In this part you will:

*   Collect exchange rate data using an API
*   Store the data as a CSV

For this lab, we are going to be using Python and several Python libraries. Some of these libraries might be installed in your lab environment or in SN Labs. Others may need to be installed by you. The cells below will install these libraries when executed.

In [ ]:
#!mamba install pandas==1.3.3 -y
#!mamba install requests==2.26.0 -y

## Imports

Import any additional libraries you may need here.

In [ ]:
import requests
import pandas as pd

## Extract Data Using an API

Using ExchangeRate-API we will extract currency exchange rate data. Use the below steps to get the access key and to get the data.

1.  Open the url : [https://exchangeratesapi.io/](https://exchangeratesapi.io/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2022-01-01) and click on **Get Free API Key**.
2.  Subscribe for Free plan and Sign-in with the Google Account.
3.  Once the account is created you will be redirected to [https://apilayer.com](https://apilayer.com/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2022-01-01) website.
4.  Now, click on the **user icon** and click **Account** as shown below:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/Images/account.png"/>

3.  Scroll down and you will get the API Key section. Copy the API key and use in the url in Question 1.

### Call the API

<b> Question 1</b> Using the `requests` library call the endpoint given above and save the text, remember the first few characters of the output:

In [6]:
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests  # this module helps us to download a web page

In [15]:
# Write your code here
url = "https://api.apilayer.com/exchangerates_data/latest?base=EUR&apikey=R1UDf4uAyFWSPUOmjANzXDjcvjIcjbxd" #Make sure to change ******* to your API key.

In [16]:
data  = requests.get(url).text 
soup = BeautifulSoup(data,"html.parser")  # create a soup object using the variable 'data'
soup

{
    "success": true,
    "timestamp": 1670203263,
    "base": "EUR",
    "date": "2022-12-05",
    "rates": {
        "AED": 3.874304,
        "AFN": 93.043312,
        "ALL": 116.807145,
        "AMD": 417.178383,
        "ANG": 1.901006,
        "AOA": 534.019365,
        "ARS": 177.086525,
        "AUD": 1.545742,
        "AWG": 1.901291,
        "AZN": 1.793059,
        "BAM": 1.957793,
        "BBD": 2.129736,
        "BDT": 108.065578,
        "BGN": 1.974299,
        "BHD": 0.397799,
        "BIF": 2184.120429,
        "BMD": 1.054808,
        "BND": 1.423327,
        "BOB": 7.28871,
        "BRL": 5.505566,
        "BSD": 1.054858,
        "BTC": 6.1258546e-05,
        "BTN": 85.686134,
        "BWP": 13.61055,
        "BYN": 2.663471,
        "BYR": 20674.233945,
        "BZD": 2.126232,
        "CAD": 1.417525,
        "CDF": 2162.35622,
        "CHF": 0.987849,
        "CLF": 0.033774,
        "CLP": 931.921873,
        "CNY": 7.408549,
        "COP": 5035.230773,
        "CRC": 630.912735,
        "CUC": 1.054808,
        "CUP": 27.952408,
        "CVE": 110.375694,
        "CZK": 24.370811,
        "DJF": 187.778321,
        "DKK": 7.437418,
        "DOP": 57.729897,
        "DZD": 145.733154,
        "EGP": 25.89015,
        "ERN": 15.822118,
        "ETB": 56.385749,
        "EUR": 1,
        "FJD": 2.315251,
        "FKP": 0.857756,
        "GBP": 0.857717,
        "GEL": 2.842667,
        "GGP": 0.857756,
        "GHS": 14.872916,
        "GIP": 0.857756,
        "GMD": 65.398274,
        "GNF": 9095.12139,
        "GTQ": 8.278202,
        "GYD": 220.801439,
        "HKD": 8.208779,
        "HNL": 26.041116,
        "HRK": 7.556014,
        "HTG": 149.255687,
        "HUF": 409.575031,
        "IDR": 16223.841386,
        "ILS": 3.59394,
        "IMP": 0.857756,
        "INR": 85.846329,
        "IQD": 1539.50395,
        "IRR": 44723.853459,
        "ISK": 148.828198,
        "JEP": 0.857756,
        "JMD": 162.266735,
        "JOD": 0.748172,
        "JPY": 141.846314,
        "KES": 129.161462,
        "KGS": 89.078114,
        "KHR": 4338.450981,
        "KMF": 492.365853,
        "KPW": 949.327106,
        "KRW": 1365.738861,
        "KWD": 0.32332,
        "KYD": 0.879082,
        "KZT": 495.92736,
        "LAK": 18266.419176,
        "LBP": 1604.873379,
        "LKR": 388.698721,
        "LRD": 162.440356,
        "LSL": 18.490522,
        "LTL": 3.114573,
        "LVL": 0.638043,
        "LYD": 5.12648,
        "MAD": 11.135868,
        "MDL": 20.658518,
        "MGA": 4609.002314,
        "MKD": 61.676855,
        "MMK": 2215.107305,
        "MNT": 3613.216988,
        "MOP": 8.457882,
        "MRO": 376.566223,
        "MUR": 46.042427,
        "MVR": 16.112207,
        "MWK": 1082.665793,
        "MXN": 20.451332,
        "MYR": 4.621105,
        "MZN": 67.328665,
        "NAD": 18.448198,
        "NGN": 468.514022,
        "NIO": 38.511623,
        "NOK": 10.279372,
        "NPR": 137.097493,
        "NZD": 1.644034,
        "OMR": 0.406177,
        "PAB": 1.054858,
        "PEN": 4.031843,
        "PGK": 3.717428,
        "PHP": 58.867728,
        "PKR": 236.620904,
        "PLN": 4.670308,
        "PYG": 7608.330305,
        "QAR": 3.840535,
        "RON": 4.926794,
        "RSD": 117.422762,
        "RUB": 63.868416,
        "RWF": 1141.715012,
        "SAR": 3.964496,
        "SBD": 8.681693,
        "SCR": 13.721661,
        "SDG": 599.660644,
        "SEK": 10.874621,
        "SGD": 1.423205,
        "SHP": 1.452892,
        "SLE": 19.450645,
        "SLL": 19434.834912,
        "SOS": 600.714183,
        "SRD": 33.299232,
        "STD": 21832.392936,
        "SVC": 9.230257,
        "SYP": 2650.235156,
        "SZL": 18.324778,
        "THB": 36.527921,
        "TJS": 10.616647,
        "TMT": 3.691827,
        "TND": 3.404901,
        "TOP": 2.468357,
        "TRY": 19.663832,
        "TTD": 7.147668,
        "TWD": 32.148959,
        "TZS": 2459.811817,
        "UAH": 38.759071,
        "UGX": 3934.445809,
        "USD": 1.054808,
        "UYU": 41.564685,
        "UZS": 11874.168463,
        "VEF": 1184826.301642,
        "VND": 25700.393371,
        "VUV": 123.528405,
        "WST": 2.833967,
        "XAF": 656.615512,
        "XAG": 0.045117,
        "XAU": 0.000585,
        "XCD": 2.850671,
        "XDR": 0.798601,
        "XOF": 656.615512,
        "XPF": 119.976614,
        "YER": 264.097515,
        "ZAR": 18.29675,
        "ZMK": 9494.535745,
        "ZMW": 18.116369,
        "ZWL": 339.647699
    }
}

In [17]:
#OTHER METHOD
import requests
import pandas as pd
import json
data = json.loads(requests.get(url).text)
data

{'success': True,
 'timestamp': 1670203323,
 'base': 'EUR',
 'date': '2022-12-05',
 'rates': {'AED': 3.874182,
  'AFN': 93.040371,
  'ALL': 116.803452,
  'AMD': 417.165196,
  'ANG': 1.900946,
  'AOA': 534.002483,
  'ARS': 176.64852,
  'AUD': 1.545651,
  'AWG': 1.901231,
  'AZN': 1.788977,
  'BAM': 1.957732,
  'BBD': 2.129669,
  'BDT': 108.062162,
  'BGN': 1.974237,
  'BHD': 0.397786,
  'BIF': 2184.051385,
  'BMD': 1.054775,
  'BND': 1.423282,
  'BOB': 7.288479,
  'BRL': 5.505397,
  'BSD': 1.054825,
  'BTC': 6.1265457e-05,
  'BTN': 85.683425,
  'BWP': 13.61012,
  'BYN': 2.663387,
  'BYR': 20673.580396,
  'BZD': 2.126165,
  'CAD': 1.417453,
  'CDF': 2162.287909,
  'CHF': 0.987904,
  'CLF': 0.033773,
  'CLP': 931.891466,
  'CNY': 7.408315,
  'COP': 5035.071601,
  'CRC': 630.892791,
  'CUC': 1.054775,
  'CUP': 27.951525,
  'CVE': 110.372205,
  'CZK': 24.373099,
  'DJF': 187.772385,
  'DKK': 7.437535,
  'DOP': 57.728072,
  'DZD': 145.728547,
  'EGP': 25.890503,
  'ERN': 15.821618,
  'ETB': 56.383966,
  'EUR': 1,
  'FJD': 2.315177,
  'FKP': 0.857729,
  'GBP': 0.857674,
  'GEL': 2.842661,
  'GGP': 0.857729,
  'GHS': 14.872446,
  'GIP': 0.857729,
  'GMD': 65.395923,
  'GNF': 9094.833877,
  'GTQ': 8.27794,
  'GYD': 220.794459,
  'HKD': 8.208429,
  'HNL': 26.040293,
  'HRK': 7.55577,
  'HTG': 149.250969,
  'HUF': 409.536918,
  'IDR': 16223.328522,
  'ILS': 3.593831,
  'IMP': 0.857729,
  'INR': 85.812815,
  'IQD': 1539.455284,
  'IRR': 44722.439247,
  'ISK': 148.827018,
  'JEP': 0.857729,
  'JMD': 162.261606,
  'JOD': 0.748152,
  'JPY': 141.833948,
  'KES': 129.157085,
  'KGS': 89.075537,
  'KHR': 4338.313835,
  'KMF': 492.350282,
  'KPW': 949.297096,
  'KRW': 1365.664034,
  'KWD': 0.32331,
  'KYD': 0.879054,
  'KZT': 495.911683,
  'LAK': 18265.841742,
  'LBP': 1604.849765,
  'LKR': 388.686434,
  'LRD': 162.435544,
  'LSL': 18.490118,
  'LTL': 3.114475,
  'LVL': 0.638023,
  'LYD': 5.125933,
  'MAD': 11.135516,
  'MDL': 20.657865,
  'MGA': 4608.856615,
  'MKD': 61.674905,
  'MMK': 2215.037281,
  'MNT': 3613.102768,
  'MOP': 8.457615,
  'MRO': 376.554319,
  'MUR': 46.040937,
  'MVR': 16.111701,
  'MWK': 1082.631568,
  'MXN': 20.450875,
  'MYR': 4.62102,
  'MZN': 67.326513,
  'NAD': 18.448433,
  'NGN': 468.49897,
  'NIO': 38.510405,
  'NOK': 10.279485,
  'NPR': 137.09316,
  'NZD': 1.644014,
  'OMR': 0.406165,
  'PAB': 1.054825,
  'PEN': 4.031716,
  'PGK': 3.717311,
  'PHP': 58.85589,
  'PKR': 236.613424,
  'PLN': 4.67017,
  'PYG': 7608.089792,
  'QAR': 3.840437,
  'RON': 4.927277,
  'RSD': 117.41905,
  'RUB': 63.866495,
  'RWF': 1141.678921,
  'SAR': 3.964374,
  'SBD': 8.681419,
  'SCR': 13.721228,
  'SDG': 599.63692,
  'SEK': 10.874789,
  'SGD': 1.423186,
  'SHP': 1.452848,
  'SLE': 19.45003,
  'SLL': 19434.220159,
  'SOS': 600.695788,
  'SRD': 33.29819,
  'STD': 21831.702775,
  'SVC': 9.229965,
  'SYP': 2650.151377,
  'SZL': 18.324198,
  'THB': 36.558585,
  'TJS': 10.616312,
  'TMT': 3.691711,
  'TND': 3.404836,
  'TOP': 2.468279,
  'TRY': 19.657854,
  'TTD': 7.147442,
  'TWD': 32.153959,
  'TZS': 2459.733894,
  'UAH': 38.757846,
  'UGX': 3934.321434,
  'USD': 1.054775,
  'UYU': 41.563371,
  'UZS': 11873.7931,
  'VEF': 1184788.84717,
  'VND': 25699.580936,
  'VUV': 123.5245,
  'WST': 2.833877,
  'XAF': 656.594755,
  'XAG': 0.045093,
  'XAU': 0.000585,
  'XCD': 2.850581,
  'XDR': 0.798576,
  'XOF': 656.594755,
  'XPF': 119.927316,
  'YER': 264.089122,
  'ZAR': 18.296108,
  'ZMK': 9494.22747,
  'ZMW': 18.115796,
  'ZWL': 339.636962}}

### Save as DataFrame

<b> STEP2</b>  Using the data gathered turn it into a `pandas` dataframe. The dataframe should have the Currency as the index and `Rate` as their columns. Make sure to drop unnecessary columns.

In [22]:
type(data)

dict

In [40]:
dataframe = pd.DataFrame(columns=["Currency", "Rate"])

for k,v in data['rates'].items():
    dataframe = dataframe.append({"Currency": k, "Rate": v}, ignore_index=True)

In [41]:
dataframe

    Currency         Rate
0        AED     3.874182
1        AFN    93.040371
2        ALL   116.803452
3        AMD   417.165196
4        ANG     1.900946
..       ...          ...
164      YER   264.089122
165      ZAR    18.296108
166      ZMK  9494.227470
167      ZMW    18.115796
168      ZWL   339.636962

[169 rows x 2 columns]

In [42]:
# Drop unnescessary columns
dataframe.set_index("Currency", inplace=True, drop=True)
dataframe

                 Rate
Currency
AED          3.874182
AFN         93.040371
ALL        116.803452
AMD        417.165196
ANG          1.900946
...               ...
YER        264.089122
ZAR         18.296108
ZMK       9494.227470
ZMW         18.115796
ZWL        339.636962

[169 rows x 1 columns]

### Load the Data

Using the dataframe save it as a CSV names `exchange_rates_1.csv`.

In [ ]:
# Save the Dataframe
dataframe.to_csv("exchange_rates_1.csv")